import pandas as pd
df = pd.read_csv('AIML Dataset.csv')
print("Dataset Head:")
print(df.head())
print('\nDataset Shape:', df.shape)
print('\nColumns:', list(df.columns))
print('\nData Types:')
print(df.dtypes)
print('\nMissing Values:')
print(df.isnull().sum())
print('\nisFraud Distribution:')
print(df['isFraud'].value_counts())
print('\nValue Counts by Type:')
print(df['type'].value_counts())
